[version]
current = "0.5.4"
regex = """
  (?P<major>\\d+)
  \\
  (?P<minor>\\d+)
  \\
  (?P<patch>\\d+)
  (\\-
    (?P<extra>.+)
  )?
  """

[git]
message_template = "Bump version to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "src/rompy/__init__.py"
search = '__version__ = "{current_version}"'
